---
name: Lint OpenAPI Descriptions

on:
  - push

jobs:
  build:
    name: Lint OpenAPI Descriptions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Yaml Lint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: 'descriptions/**/*.yaml'
          yamllint_strict: false
          yamllint_config_filepath: '.yamllint-config.yml'
          yamllint_comment: true
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: JSON Lint
        run: npm run lint
      - name: OpenAPI Lint
        uses: mattpage/redocly-cli-lint-action@v0.0.1
        with:
          entrypoints: 'descriptions/**/*.yaml'
          config: '.redocly.yml'
